// autogenerated by tools/subsetfont.js 29/08/2026
module.exports = {
   content_copy: String.fromCodePoint(0xe14d),
   qr_code_2: String.fromCodePoint(0xe00a),
   check_circle: String.fromCodePoint(0xf0be),
   delete: String.fromCodePoint(0xe92e)
}