// generate a subset font out of a larger one, for optimising icon font packs down to only the used icons
// USAGE: node tools/subsetfont.js <input font/codepoint path without extension> <file with list of codepoints wanted> <output font path without extension>

const fs = require("fs");
const path = require("path");
const {exec} = require("child_process");

let args = process.argv.slice(2);

const codepoints = path.resolve(args[0] + ".codepoints");
const font = path.resolve(args[0] + ".woff2");
const outFont = path.resolve(args[2] + ".woff2");
const outJs = path.resolve(args[2] + ".js");
const wantedCodepoints = fs.readFileSync(path.resolve(args[1])).toString().split("\n").map(x => x.split(" ")[0]);
const allCodepoints = Object.fromEntries(fs.readFileSync(codepoints).toString().split("\n").map(x => x.split(" ")));

let outputTypescript = `// autogenerated by tools/subsetfont.js ${new Date().toLocaleDateString("en-GB")}\nmodule.exports = {\n`
let outputCharacters = "";
for(let codepoint of wantedCodepoints) {
    outputCharacters += `,U+${allCodepoints[codepoint]}`;
    outputTypescript += `   ${codepoint}: String.fromCodePoint(0x${allCodepoints[codepoint]}),\n`
}
outputCharacters = outputCharacters.slice(1);
outputTypescript = outputTypescript.slice(0, -2) + "\n}";

// yes i know. but this is a dev tool, the only person you are pwning is yourself
exec(`pyftsubset ${font} --unicodes="${outputCharacters}" --output-file=${outFont}`, (error, stdout, stderr) => {
    console.log(stdout);
    console.log(stderr);

    console.log(`output size: ${fs.statSync(outFont).size / 1000}kb`);
});

fs.writeFileSync(outJs, outputTypescript);