name: Build Release Artifacts

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4.1.0
      - name: Build package
        run: ./ci/createpackage.sh
      - name: Upload Artifact
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "./ciout/filecan.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
